%{
%% Saves paramater data provided in the form generated by autfit to a csv
%%
%% csv will have the following format:
%% header 1: parth of the initial parameter file
%% header 2: value of errorTolorance during fitting
%% data: one row for each parameter
%}

function saveParamStats( paramData, paramHeaders, filePath, fileName )
global idxPar;
convert2med = [ ...
	idxPar.uDivFirst, idxPar.uDthFirst, ...
	idxPar.uDivBlast, idxPar.uDthBlast];
paramData(convert2med,:) = exp(paramData(convert2med,:));

fullFileName = [filePath , '/', fileName];

% create file and write path headers
%dlmwrite(fullFileName, paramHeaders(1,:));

file=fopen(fullFileName,'wt');

%[rows,~]=size(paramHeaders);

fprintf(file,'%s,',paramHeaders{1,1:end-1});
fprintf(file,'%s\n',paramHeaders{1,end});

fclose(file);

% append errTol headers
dlmwrite(fullFileName, paramHeaders(2,:), '-append');

% append concentration headers
dlmwrite(fullFileName, paramHeaders(3,:), '-append');

% write rest of data
dlmwrite(fullFileName, paramData, '-append', 'precision', 30);

end

